"""Build bench/out/listen.html — Phase 0 listening test (serve repo root over http)."""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "bench" / "out"
Q = OUT / "1.7B-Base-6bit"
VOICES = {"ru_male": "Russian · male", "ru_female": "Russian · female",
          "en_male": "English · male", "en_female": "English · female"}


def audio(path: Path, caption: str = "") -> str:
    rel = "/" + path.relative_to(ROOT).as_posix()
    text = path.with_suffix(".txt")
    cap = caption or (text.read_text(encoding="utf-8") if text.exists() else "")
    return (f'<figure><figcaption>{html.escape(cap)}</figcaption>'
            f'<audio controls preload="none" src="{rel}"></audio></figure>')


def voice_section(v: str, label: str) -> str:
    vdir = ROOT / "voices" / v
    desc = (vdir / "description.txt").read_text(encoding="utf-8").strip()
    cols = []
    for c in ("cand0", "cand1"):
        items = [audio(vdir / f"{c}.wav", "Reference clip (designed voice)")]
        items += [audio(Q / v / f"b8_listen_{c}" / f"seg{i}.wav") for i in range(3)]
        cols.append(f'<div class="cand"><h4>Candidate {c[-1]}</h4>{"".join(items)}</div>')
    return (f'<section><h3>{label}</h3><p class="desc">“{html.escape(desc)}”</p>'
            f'<div class="cands">{"".join(cols)}</div></section>')


def compare_section() -> str:
    rows = []
    for i in range(4):
        qwen = audio(Q / "ru_male" / "b8_listen_cand0" / f"seg{i}.wav", "Qwen3 · ru_male cand 0")
        sil = [audio(OUT / "silero" / s / f"prose_{i}.wav", f"Silero v5 · {s}") for s in ("aidar", "xenia")]
        src = (OUT / "silero" / "aidar" / f"prose_{i}.txt").read_text(encoding="utf-8")
        rows.append(f'<div class="row"><p class="src">{html.escape(src)}</p>'
                    f'<div class="trio">{qwen}{"".join(sil)}</div></div>')
    return "".join(rows)


def traps_section() -> str:
    rows = []
    for v in ("ru_male", "en_male"):
        for wav in sorted((Q / v / "b8_traps").glob("seg*.wav")):
            i = int(wav.stem[3:])
            extra = ""
            sil = OUT / "silero" / "aidar" / f"trap_{i}.wav"
            if v == "ru_male" and sil.exists():
                extra = audio(sil, "Silero v5 · aidar")
            src = wav.with_suffix(".txt").read_text(encoding="utf-8")
            rows.append(f'<div class="row"><p class="src">{html.escape(src)}</p><div class="trio">'
                        f'{audio(wav, "Qwen3 · " + v)}{extra}</div></div>')
    return "".join(rows)


def bench_table() -> str:
    recs = [json.loads(l) for l in (OUT / "results.jsonl").read_text().splitlines()]
    keep = [r for r in recs if r["tag"] in ("_guarded",) or r["tag"].startswith("_g2p")]
    body = "".join(f"<tr><td>{r['model']}</td><td>{r['voice']}</td><td>{r['batch']}</td>"
                   f"<td>{r['tag'].strip('_') or '-'}</td><td>{r['x_realtime']}×</td></tr>" for r in keep)
    return ("<table><tr><th>Model</th><th>Voice</th><th>Batch</th><th>Run</th><th>Speed</th></tr>"
            f"{body}</table>")


PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MyTTS Listening Test</title>
<style>
:root{--bg:#f6f5f2;--card:#fff;--ink:#1d1d1f;--mute:#6e6e73;--line:#e3e1dc;--acc:#b4532a}
@media (prefers-color-scheme:dark){:root{--bg:#141414;--card:#1e1e1e;--ink:#ececec;--mute:#9a9a9a;--line:#2c2c2c;--acc:#e58a5f}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 -apple-system,system-ui,sans-serif}
main{max-width:1100px;margin:auto;padding:24px 16px 80px}h1{font-size:28px;margin:0 0 4px}
h2{margin:40px 0 8px;font-size:20px;border-bottom:2px solid var(--acc);padding-bottom:4px}
section{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;margin:14px 0}
h3{margin:0 0 4px}.desc,.lead{color:var(--mute)}.desc{font-style:italic;font-size:13px}
.cands{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:700px){.cands{grid-template-columns:1fr}}
.cand h4{margin:8px 0;color:var(--acc)}figure{margin:0 0 10px}figcaption{font-size:13px;margin-bottom:3px}
audio{width:100%;height:36px}.row{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:12px 16px;margin:10px 0}
.src{margin:0 0 8px;font-weight:500}.trio{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}
table{border-collapse:collapse;background:var(--card);width:100%}td,th{border:1px solid var(--line);padding:6px 10px;text-align:left}
</style></head><body><main>
<h1>MyTTS · Phase 0 listening test</h1>
<p class="lead">Qwen3-TTS 1.7B (6-bit, batch 8), cloning voices generated by VoiceDesign.
Pick one candidate per voice (or say “redesign” with a hint, e.g. “deeper, slower”).</p>
<h2>1 · Narrator voices</h2>@@voices@@
<h2>2 · Russian: Qwen3 vs Silero v5</h2><p class="lead">Silero stresses words correctly but sounds more synthetic; it's also non-commercial (CC BY-NC-SA).</p>@@compare@@
<h2>3 · “Trap” sentences — raw text, no normalization yet</h2><p class="lead">Numbers, abbreviations, homographs, missing ё, English words. The real pipeline will normalize these first; this shows why that's needed.</p>@@traps@@
<h2>4 · Speed (real-time multiple, higher is better)</h2>@@bench@@
</main></body></html>"""

if __name__ == "__main__":
    parts = dict(voices="".join(voice_section(v, l) for v, l in VOICES.items()),
                 compare=compare_section(), traps=traps_section(), bench=bench_table())
    page = PAGE
    for k, v in parts.items():
        page = page.replace(f"@@{k}@@", v)
    (OUT / "listen.html").write_text(page, encoding="utf-8")
    print(OUT / "listen.html")
